### ISSUE TITLE
Continuous improvement on SARIF support

### ISSUE THREAD

**Issue by chao2zhang** [detekt/detekt#3360]
This issue lists all the improvements after we built a basic SARIF support #3045
- [x] Enable SARIF output by default in Gradle+CLI. See https://github.com/detekt/detekt/pull/3268
- [x] Enable relative path by default. See https://github.com/detekt/detekt/pull/3359#discussion_r554181042
- [x] Add documentation and samples for relative path, severity, and Github integration for SARIF
- [x] Add integration tests with GradleKit to verify SARIF, relative path, and configurable severity once a version is published. The publishing constraint can be lifted once https://github.com/detekt/detekt/issues/3324 is completed.
- [x] Fix absolute path usage in the message of CodeSmell -> This is fixed by #3386
- [x] In Detekt 2.0, remove the deprecated Severity -> This is addressed by #6399 
- [x] In Detekt 2.0, refactor the implementation of SeverityLevel so it can be configured per issue. https://github.com/detekt/detekt/pull/3310#pullrequestreview-556036609
- [ ] Plan to improve the CorrectSmell message so that we do not fall back to the issue description.
- [x] Merge SARIF support from all modules to generate a single top-level report

**Comment by schalkms** [comment]
Good summary!

**Comment by madlymad** [comment]
Maybe some "SARIF" validation is also required. I noticed a case where an complete empty `.kt` file was part of the repository and the created SARIF report was invalid

**Comment by BraisGabin** [comment]
> Maybe some "SARIF validation" is also required in the unit testing level. I noticed a case where a completely empty `.kt` file was part of the repository and the created SARIF report was invalid.

If that's the case, please open an issue with a way to reproduce it. That's a bug and we should fix it. It's not an improvement.

**Comment by BraisGabin** [comment]
Can we close this one now? I think that sarif is in a good state right now. If there are things to do I think that we should have separated issues for it. Also I don't fully understand what we need to do to finish some of those points that are still missing. Do you recall them @chao2zhang?

**Comment by chao2zhang** [comment]
It's been a while since I work any project involving Kotlin 😅 . I have verified the check list in the original summary, only one issue remaining `Plan to improve the CorrectSmell message so that we do not fall back to the issue description.` but I couldn't find reference of `CorrectSmell` in the codebase now.

I would also vote for closing this issue.
