### ISSUE TITLE
Remove all usages of `MutliRule` in detekt code base

### ISSUE THREAD

**Issue by marschwar** [detekt/detekt#5192]
We decided to remove the `MultiRule` construct for all the reasons mentioned in #4240. As it is part of the API we cannot remove support for it just yet but we can change all those places where we use it for first party rules.

This issue keeps track of all the tasks necessary.

- [x] Replace `EmptyBlocks` mutli rule (#5208)
- [x] Replace `FileParsingRule` mutli rule (#5193)
- [x] Replace `KDocStyle`mutli rule (#5207)
- [x] Replace `KtLintMultiRule` (#6094)
- [x] Replace `NamingRules`multi rule (#5212)
- [x] Remove multi rule support in config and documentation generation (blocked until multi rule is no longer used in code base) (#6094)
- [ ] Remove `MultiRule` (#6288)

**Comment by chao2zhang** [comment]
KtLintMultiRule seems to be the last multi rule in source set. I will take a stab at it in https://github.com/detekt/detekt/pull/5312

**Comment by cortinico** [comment]
> I will probably still perform the ktlint upgrades first, then refactor off `MultiRule`.

This is still a think, as suggested by @chao2zhang.
The last multirule is the KtLint one

**Comment by marschwar** [comment]
Have you started to work on it @chao2zhang? I could pick it up If you like.
